# fly.toml app configuration file generated for portfolio-api-hjk on 2025-02-07T01:08:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-api-hjk'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
